server:
  port: 9010
  servlet:
    context-path: /api/risk
spring:
  application:
    name: risk-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.126:3306/private_bank?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: zyx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      uri: http://localhost:9001
    discovery:
      enabled: true
      service-id: discovery-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true