eureka:
  client:
    service-url:
        defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
spring:
  cloud:
    gateway:
      routes:
        - id: advisor-service
          uri: lb://advisor-service
          predicates:
            - Path=/api/advisor/**
        - id: approval-service
          uri: lb://approval-service
          predicates:
            - Path=/api/approval/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/client/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/portfolio/**
        - id: risk-service
          uri: lb://risk-service
          predicates:
            - Path=/api/risk/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/api/trade/**
  application:
    name: gateway-service
  main:
    web-application-type: reactive
server:
  address: localhost
  port: 9003