server:
  port: 9002

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
          git:
            uri: https://github.com/zyx666yyds/private-bank.git
            username: zyx666yyds
            password: zyx20020207**
            default-label: master
            search-paths: config


